# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Path of Exile Item Affixes
description: >
    Description...
repository: blkice/poeaffix.info

collections:
    mods:
        output: true
        permalink: /:collection/:name

defaults:
    - scope:
        type: mods
      values:
        layout: mod-page
    - scope:
        path: _mods/weapon
      values:
        category: Weapon
    - scope:
        path: _mods/armour
      values:
        category: Body Armour
    - scope:
        path: _mods/helmet
      values:
        category: Helmet

# -----------------------------------------------------------------------------
# Build settings
# -----------------------------------------------------------------------------
markdown: kramdown

# -----------------------------------------------------------------------------
# Sass settings
# -----------------------------------------------------------------------------
sass:
    style: expanded

exclude:
    - Gemfile
    - Gemfile.lock
    - tools
