title: Path of Exile Item Affixes
author: pblkice
email: private.blackice@gmail.com

description: >
    Path of Exile Item Affixes

github_username: pblackice

collections:
    mods:
        output: true
        permalink: /:name

defaults:
  - scope:
      path: ""
      type: mods
    values:
      layout: mods-page
  - scope:
      path: _mods/weapon
    values:
      category: Weapon
  - scope:
      path: _mods/jewel
    values:
      category: Jewel

sass:
    style: compressed

theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - tools
